# Generated by Django 5.0.6 on 2024-07-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0003_sets_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
